Metrics/LineLength:
  Max: 150
  IgnoredPatterns: ['\A#']

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 100

Metrics/AbcSize:
  Max: 30

Style/MixinUsage:
  Enabled: false

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: false
  # Checks the style of children definitions at classes and modules.
  #
  # Basically there are two different styles:
  #
  # `nested` - have each child on a separate line
  #   class Foo
  #     class Bar
  #     end
  #   end
  #
  # `compact` - combine definitions as much as possible
  #   class Foo::Bar
  #   end
  #
  # The compact style is only forced, for classes / modules with one child.
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

Style/NumericLiterals:
  Description: 'Add underscores to large numeric literals to improve their readability.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics'
  Enabled: true
  MinDigits: 5
