version: '3.1'
services:
  production_db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data 
    environment:
      POSTGRES_DB: blog-rails-sample_test
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: admin123 
      POSTGRES_USER: postgresadmin


  # production_db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: blog-rails-sample_production
  #     POSTGRES_HOST_AUTH_METHOD: "trust"
  #     POSTGRES_PASSWORD: admin123 
  #     POSTGRES_USER: postgresadmin



  # # development_db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: blog-rails-sample_development
  #     POSTGRES_HOST_AUTH_METHOD: "trust"
  #     POSTGRES_PASSWORD: admin123 
  #     POSTGRES_USER: postgresadmin

  # default_db:
  #   image: postgres
  #   # ports:
  #   #   - "5432:5432"
  #   environment:
  #     POSTGRES_DB: blog-rails-sample_default
  #     POSTGRES_HOST_AUTH_METHOD: "trust"
  #     POSTGRES_PASSWORD: admin123 
  #     POSTGRES_USER: postgresadmin

